name: Docker Image Build Test CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Building Swiss on FHIR
        run: |
          docker buildx build \
          --tag omarhoblos/swiss-on-fhir:latest \
          --platform linux/amd64,linux/arm64 .
