name: Docker Image Build Test CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Building Swiss on FHIR
        run: |
          docker buildx build \
          --tag omarhoblos/swiss-on-fhir:latest \
          --platform linux/amd64,linux/arm64 .
