name: Docker Image Build Test CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Install python3
        run: sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt install -y python3
      - name: Test python3
        run: python3 --version
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      - name: Building Swiss on FHIR
        run: |
          docker buildx build \
          --tag omarhoblos/swiss-on-fhir:latest \
          --platform linux/amd64,linux/arm64 .
